language: python
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install codecov
install:
  - pip install -r docs/requirements.txt
script:
  - coverage run -m pytest
after_success:
  - codecov # submit coverage